baseURL = 'https://kubeskills.com/'
languageCode = 'en-us'
title = 'KubeSkills'

[permalinks]
    blog = "/:filename/"
[menu]
    [[menu.main]]
        name = "Blog"
        url = "https://blog.kubeskills.com"
        weight = 1
        pre = "<i class='bi bi-box-arrow-up-right'></i>"
        params = { external = true }
    [[menu.main]]
        name= "Courses"
        url = "/courses/"
        weight = 2
    [[menu.main]]
        name = "Community"
        url = "https://community.kubeskills.com"
        weight = 3
        params = { external = true }
[params]
  containerMaxWidth = "700px"
  dateFormat = "Sept 2, 2023"
  homeText = "KubeSkills"
  author = "KubeSkills"
  description = "The #1 Kubernetes learning community"
  keywords = "Kubernetes, DevOps, Cloud, Security"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files